kind: ConfigMap
apiVersion: v1
metadata:
  name: cle-configuration-api-pf-prod-e-configmap
  namespace: prod-internal
data:
  PF_SERVICE_NAME: "be__premfina_api__prod-e"
  PF_PROCESSORS_COUNT: "50"
  PF_WEBSOURCE: "avantia"
  PF_DELAY_NEWAGREEMENTSFILE: "100"
  PF_PLACES_APP_UUID: "INTEGRATIONS_API"
  PF_PREFERRED_PAYMENT_DAY_PLUS: "5"
  PF_DATAVALIDATION_APPLICATION_CLIENT_NAME: "INTEGRATIONS_API"
  PF_USE_PROCESS_DATE: "false"
  PF_DEFAULT_FEE: "10.00"
  MTA_EXCEPTION_SEVERITY: "F,W"
  PF_TEST_AGREEMENTS_POLICY_REFERENCES: "PFTEST1"
  PF_API_POST_CASH_CSV_DIR: "/"
  PF_FILE_NEWMAG_OUTPUTDIR: "/"
  PF_FILE.PLAYER.OUTPUTDIR: "/"
  PF_FILE.PLAYER.FINALDIR: "/"
  PF_FILE.PLAYER.REPORTDIR: "/"
