kind: ConfigMap
apiVersion: v1
metadata:
  name: ingresses-configmap
  namespace: staging-internal
data:
  elasticsearch: elastic-mon.internal.staging.premfina.com
  kibana: kibana.app.staging.premfina.com
  be__accounting: be-accounting.internal.staging.premfina.com
  be__bff_mobile_app: be-bff-mobile-app.internal.staging.premfina.com
  be__bff_mobile_app_rest: be-bff-mobile-app-rest.services.staging.premfina.com
  be__bff_portal: be-bff-portal.internal.staging.premfina.com
  be__bff_portal_rest: be-bff-portal-rest.services.staging.premfina.com
  be__db_identities: be-db-identities.internal.staging.premfina.com
  be__insurer_pricing_engine: be-insurer-pricing-engine.internal.staging.premfina.com
  be__insurer_policies: be-insurer-policies.internal.staging.premfina.com
  be__verifications_email: be-verifications-email.internal.staging.premfina.com
  be__nashville: be-nashville.internal.staging.premfina.com
  be__ocr_reader: be-ocr-reader.internal.staging.premfina.com
  be__text_parser: be-text-parser.internal.staging.premfina.com
  be__user_manager: be-user-manager.internal.staging.premfina.com
  be__places: be-places.app.staging.premfina.com,be-places.internal.staging.premfina.com
  fe__portal: "*.staging.premfina.com"
  be__funders: be-funders.internal.staging.premfina.com
  be__document_renderer: be-document-renderer.internal.staging.premfina.com
  be__esignatures_e_sign_co_uk: be-esignatures-e-sign-co-uk.internal.staging.premfina.com
  be__esignatures_e_sign_co_uk_pub: e-sign-co-uk.services.staging.premfina.com
  be__bank_checker_experian: be-bank-checker-experian.internal.staging.premfina.com
  be__bank_checker: be-bank-checker.internal.staging.premfina.com
  be__funders_importer: be-funders-importer.internal.staging.premfina.com
  be__web_sockets: be-web-sockets.internal.staging.premfina.com
  be__global_workspace_auth: be-global-workspace-auth.internal.staging.premfina.com