kind: ConfigMap
apiVersion: v1
metadata:
  name: cle-configuration-api-pf-rnd-configmap
  namespace: dev-internal
data:
  PF_PROCESSORS_COUNT: "50"
  PF_WEBSOURCE: "Home Emergency Assist"
  PF_DELAY_NEWAGREEMENTSFILE: "500"
  PF_PLACES_APP_UUID: "INTEGRATIONSAPI"
  PF_PREFERRED_PAYMENT_DAY_PLUS: "5"
  PF_DATAVALIDATION_APPLICATION_CLIENT_NAME: "INTEGRATIONS_API"
  PF_USE_PROCESS_DATE: "true"
  PF_DEFAULT_FEE: "10.00"
  MTA_EXCEPTION_SEVERITY: "F,W"
  PF_TEST_AGREEMENTS_POLICY_REFERENCES: "PFTEST1"
  PF_API_POST_CASH_CSV_DIR: "/"
  PF_FILE_NEWMAG_OUTPUTDIR: "/"
  PF_FILE.PLAYER.OUTPUTDIR: "/"
  PF_FILE.PLAYER.FINALDIR: "/"
  PF_FILE.PLAYER.REPORTDIR: "/"
